BINARY_OPERATORS = [
    "__add__",
    "__sub__",
    "__mul__",
    "__truediv__",
    "__floordiv__",
    "__mod__",
    "__pow__",
    "__rshift__",
    "__lshift__",
    "__and__",
    "__or__",
    "__xor__",
    "__lt__",
    "__gt__",
    "__le__",
    "__ge__",
    "__eq__",
    "__ne__",
    "__matmul__",
    "__radd__",
    "__rsub__",
    "__rmul__",
    "__rtruediv__",
    "__rfloordiv__",
    "__rmod__",
    "__rpow__",
    "__rrshift__",
    "__rlshift__",
    "__rand__",
    "__ror__",
    "__rxor__",
    "__rmatmul__",
]
UNARY_OPERATORS = ["__neg__", "__pos__", "__invert__"]

ASSINGMENT_OPERATORS = [
    "__isub__",
    "__iadd__",
    "__imul__",
    "__idiv__",
    "__ifloordiv__",
    "__imod__",
    "__ipow__",
    "__irshift__",
    "__ilshift__",
    "__iand__",
    "__ior__",
    "__ixor__",
    "__neg__",
    "__pos__",
    "__invert__",
]

UNSUPPORTED_OPERATORS = [
    "__isub__",
]
